services:
  - type: web
    name: DetectiveS-server
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: python server.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
